### PR TITLE
DAOS-14803: golang update to 1.21.6

### PR DESCRIPTION
**Pull request by grom72**
Update Golang package to the latest one avaialble.

### CODE REVIEW

**Review by ryon-jensen — DISMISSED** [review]

**Review by brianjmurrell — COMMENTED** [review]
LGTM, but it's a pity that we have [4 tests failing on the downstream testing for master](https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/ci-daos-stack-go-build-toolchain-PR-24-master/3/tests).

Should these be skip-listed?

**Comment by daltonbohning** [comment]
> LGTM, but it's a pity that we have [4 tests failing on the downstream testing for master](https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/ci-daos-stack-go-build-toolchain-PR-24-master/3/tests).
> 
> Should these be skip-listed?

Those are MD on SSD failures, which still need more attention in general. I think okay for this PR to move forward

**Comment by brianjmurrell** [comment]
> > LGTM, but it's a pity that we have [4 tests failing on the downstream testing for master](https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/ci-daos-stack-go-build-toolchain-PR-24-master/3/tests).
> > Should these be skip-listed?
> 
> Those are MD on SSD failures, which still need more attention in general. I think okay for this PR to move forward

Fair enough.  But that doesn't address the additional effort that the PR owner here had to go to to determine that these failures were NOT because of this PR.  We need to be striving to reduce this noise, effort and waste of time that PR owners are suffering due to **known failures**.

**Review by brianjmurrell — DISMISSED** [review]

**Comment by brianjmurrell** [comment]
@grom72 Please add @daos-stack/release-engineering as a reviewer when you are ready for this to land.

**Comment by daltonbohning** [comment]
> Fair enough. But that doesn't address the additional effort that the PR owner here had to go to to determine that these failures were NOT because of this PR. We need to be striving to reduce this noise, effort and waste of time that PR owners are suffering due to **known failures**.

True. But FWIW, we've since reduced the default md on ssd testing. So I a new run with latest master shouldn't have these

**Review by brianjmurrell — APPROVED** [review]

**Review by ipoddubn — APPROVED** [review]

**Pull request merged**
